to root

diff --git a/fortran/test/Makefile.in b/fortran/test/Makefile.in
--- a/fortran/test/Makefile.in
+++ b/fortran/test/Makefile.in
@@ -102,11 +102,20 @@ check_PROGRAMS = $(am__EXEEXT_1)
 noinst_PROGRAMS = H5_test_buildiface$(EXEEXT)
 TESTS = $(am__EXEEXT_1)
 
+# Splitter VFD currently can't be tested with the h5_fileaccess()
+# approach due to it trying to lock the same W/O file when two
+# files are created/opened with the same FAPL that has the VFD
+# set on it. When tested with the environment variable and a
+# default FAPL, the VFD appends "_wo" to the filename when the
+# W/O path isn't specified, which works for all the tests.
+# VFD_LIST += splitter
+
 # log VFD currently has file space allocation bugs
 # VFD_LIST += log
+
+# Not currently tested with VFD tests
+# VFD_LIST += onion
 @DIRECT_VFD_CONDITIONAL_TRUE@am__append_2 = direct
-@ROS3_VFD_CONDITIONAL_TRUE@am__append_3 = ros3
-@HDFS_VFD_CONDITIONAL_TRUE@am__append_4 = hdfs
 subdir = fortran/test
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/m4/aclocal_fc.m4 \
@@ -512,7 +521,6 @@ CCDEPMODE = @CCDEPMODE@
 CC_VERSION = @CC_VERSION@
 CFLAGS = @CFLAGS@
 CLANG_SANITIZE_CHECKS = @CLANG_SANITIZE_CHECKS@
-CODESTACK = @CODESTACK@
 CONFIG_DATE = @CONFIG_DATE@
 CONFIG_MODE = @CONFIG_MODE@
 CONFIG_USER = @CONFIG_USER@
@@ -598,6 +606,7 @@ FCFLAGS_f90 = @FCFLAGS_f90@
 FCLIBS = @FCLIBS@
 FC_VERSION = @FC_VERSION@
 FGREP = @FGREP@
+FORTRAN_C_BOOL_IS_UNIQUE = @FORTRAN_C_BOOL_IS_UNIQUE@
 FORTRAN_C_LONG_DOUBLE_IS_UNIQUE = @FORTRAN_C_LONG_DOUBLE_IS_UNIQUE@
 FORTRAN_HAVE_C_LONG_DOUBLE = @FORTRAN_HAVE_C_LONG_DOUBLE@
 FSEARCH_DIRS = @FSEARCH_DIRS@
@@ -627,9 +636,11 @@ H5_UTILS_TEST_BUILDDIR = @H5_UTILS_TEST_BUILDDIR@
 H5_VERSION = @H5_VERSION@
 HADDR_T = @HADDR_T@
 HAVE_Fortran_INTEGER_SIZEOF_16 = @HAVE_Fortran_INTEGER_SIZEOF_16@
+HAVE_ISO_FORTRAN_ENV = @HAVE_ISO_FORTRAN_ENV@
 HAVE_LIBHDFS = @HAVE_LIBHDFS@
 HAVE_MERCURY = @HAVE_MERCURY@
 HAVE_PTHREAD = @HAVE_PTHREAD@
+HAVE__FLOAT16 = @HAVE__FLOAT16@
 HDF5_DOXYGEN = @HDF5_DOXYGEN@
 HDF5_DOXY_WARNINGS = @HDF5_DOXY_WARNINGS@
 HDF5_HL = @HDF5_HL@
@@ -686,6 +697,7 @@ MANIFEST_TOOL = @MANIFEST_TOOL@
 MAP_API = @MAP_API@
 MIRROR_VFD = @MIRROR_VFD@
 MKDIR_P = @MKDIR_P@
+MPI_LOGICAL_KIND = @MPI_LOGICAL_KIND@
 NM = @NM@
 NMEDIT = @NMEDIT@
 OBJDUMP = @OBJDUMP@
@@ -714,6 +726,7 @@ PAC_FORTRAN_NATIVE_INTEGER_SIZEOF = @PAC_FORTRAN_NATIVE_INTEGER_SIZEOF@
 PAC_FORTRAN_NATIVE_REAL_KIND = @PAC_FORTRAN_NATIVE_REAL_KIND@
 PAC_FORTRAN_NATIVE_REAL_SIZEOF = @PAC_FORTRAN_NATIVE_REAL_SIZEOF@
 PAC_FORTRAN_NUM_INTEGER_KINDS = @PAC_FORTRAN_NUM_INTEGER_KINDS@
+PAC_MPI_LOGICAL_KIND = @PAC_MPI_LOGICAL_KIND@
 PARALLEL = @PARALLEL@
 PARALLEL_FILTERED_WRITES = @PARALLEL_FILTERED_WRITES@
 PARALLEL_TOOLS = @PARALLEL_TOOLS@
@@ -731,6 +744,7 @@ SEARCH = @SEARCH@
 SED = @SED@
 SET_MAKE = @SET_MAKE@
 SHELL = @SHELL@
+SHOW_ALL_WARNINGS = @SHOW_ALL_WARNINGS@
 SIZE_T = @SIZE_T@
 STATIC_EXEC = @STATIC_EXEC@
 STATIC_SHARED = @STATIC_SHARED@
@@ -927,8 +941,8 @@ TEST_PROG_CHKEXE = $(TEST_PROG:=.chkexe_)
 TEST_PROG_PARA_CHKEXE = $(TEST_PROG_PARA:=.chkexe_)
 TEST_SCRIPT_CHKSH = $(TEST_SCRIPT:=.chkexe_)
 TEST_SCRIPT_PARA_CHKSH = $(TEST_SCRIPT_PARA:=.chkexe_)
-VFD_LIST = sec2 stdio core core_paged split multi family splitter \
-	$(am__append_2) $(am__append_3) $(am__append_4)
+VFD_LIST = sec2 stdio core core_paged split multi family \
+	$(am__append_2)
 
 # Test with just the native connector, with a single pass-through connector
 # and with a doubly-stacked pass-through.
@@ -1662,15 +1676,15 @@ $(TEST_PROG_CHKEXE) $(TEST_PROG_PARA_CHKEXE) dummy.chkexe_:
                 if test -n "$(HDF5_VOL_CONNECTOR)"; then \
                   echo "VOL connector: $(HDF5_VOL_CONNECTOR)" | tee -a $${log}; \
                 fi; \
-                if test -n "$(HDF5_DRIVER)"; then \
-                  echo "Virtual file driver (VFD): $(HDF5_DRIVER)" | tee -a $${log}; \
+                if test -n "$(HDF5_TEST_DRIVER)"; then \
+                  echo "Virtual file driver (VFD): $(HDF5_TEST_DRIVER)" | tee -a $${log}; \
                 fi; \
               else \
                 if test -n "$(HDF5_VOL_CONNECTOR)"; then \
                   echo "VOL connector: $(HDF5_VOL_CONNECTOR)" >> $${log}; \
                 fi; \
-                if test -n "$(HDF5_DRIVER)"; then \
-                  echo "Virtual file driver (VFD): $(HDF5_DRIVER)" >> $${log}; \
+                if test -n "$(HDF5_TEST_DRIVER)"; then \
+                  echo "Virtual file driver (VFD): $(HDF5_TEST_DRIVER)" >> $${log}; \
                 fi; \
               fi; \
               if test -n "$(REALTIMEOUTPUT)"; then \
@@ -1787,20 +1801,23 @@ build-check-p: $(LIB) $(PROGS) $(chk_TESTS)
 @MIRROR_VFD_CONDITIONAL_TRUE@  # Mirror VFD needs network configuration, etc. and isn't easy to set
 @MIRROR_VFD_CONDITIONAL_TRUE@  # reasonable defaults for that info.
 @MIRROR_VFD_CONDITIONAL_TRUE@  # VFD_LIST += mirror
-@SUBFILING_VFD_CONDITIONAL_TRUE@  # Several VFD tests fail with Subfiling since it
-@SUBFILING_VFD_CONDITIONAL_TRUE@  # doesn't currently support collective I/O
+@ROS3_VFD_CONDITIONAL_TRUE@  # This would require a custom test suite
+@ROS3_VFD_CONDITIONAL_TRUE@  # VFD_LIST += ros3
+@HDFS_VFD_CONDITIONAL_TRUE@  # This would require a custom test suite
+@HDFS_VFD_CONDITIONAL_TRUE@  # VFD_LIST += hdfs
+@SUBFILING_VFD_CONDITIONAL_TRUE@  # Subfiling has a few VFD test failures to be resolved
 @SUBFILING_VFD_CONDITIONAL_TRUE@  # VFD_LIST += subfiling
 
 # Run test with different Virtual File Driver
 check-vfd: $(LIB) $(PROGS) $(chk_TESTS)
-	@for vfd in $(VFD_LIST) dummy; do                                     \
-	    if test $$vfd != dummy; then                                      \
-	        echo "============================";                          \
-	        echo "Testing Virtual File Driver $$vfd";                     \
-	        echo "============================";                          \
-	        $(MAKE) $(AM_MAKEFLAGS) check-clean || exit 1;                \
-	        HDF5_DRIVER=$$vfd $(MAKE) $(AM_MAKEFLAGS) check || exit 1;    \
-	    fi;                                                               \
+	@for vfd in $(VFD_LIST) dummy; do                                          \
+	    if test $$vfd != dummy; then                                           \
+	        echo "============================";                               \
+	        echo "Testing Virtual File Driver $$vfd";                          \
+	        echo "============================";                               \
+	        $(MAKE) $(AM_MAKEFLAGS) check-clean || exit 1;                     \
+	        HDF5_TEST_DRIVER=$$vfd $(MAKE) $(AM_MAKEFLAGS) check || exit 1;    \
+	    fi;                                                                    \
 	done
 
 # Run test with different passthrough Virtual Object Layer Connector
diff --git a/tools/libtest/Makefile.in b/tools/libtest/Makefile.in
--- a/tools/libtest/Makefile.in
+++ b/tools/libtest/Makefile.in
@@ -105,14 +105,23 @@ PRE_UNINSTALL = :
 POST_UNINSTALL = :
 build_triplet = @build@
 host_triplet = @host@
-bin_PROGRAMS = h5tools_test_utils$(EXEEXT)
+noinst_PROGRAMS = h5tools_test_utils$(EXEEXT)
 TESTS =
+
+# Splitter VFD currently can't be tested with the h5_fileaccess()
+# approach due to it trying to lock the same W/O file when two
+# files are created/opened with the same FAPL that has the VFD
+# set on it. When tested with the environment variable and a
+# default FAPL, the VFD appends "_wo" to the filename when the
+# W/O path isn't specified, which works for all the tests.
+# VFD_LIST += splitter
 
 # log VFD currently has file space allocation bugs
 # VFD_LIST += log
+
+# Not currently tested with VFD tests
+# VFD_LIST += onion
 @DIRECT_VFD_CONDITIONAL_TRUE@am__append_1 = direct
-@ROS3_VFD_CONDITIONAL_TRUE@am__append_2 = ros3
-@HDFS_VFD_CONDITIONAL_TRUE@am__append_3 = hdfs
 subdir = tools/libtest
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/m4/aclocal_fc.m4 \
@@ -141,8 +150,7 @@ CONFIG_HEADER = $(top_builddir)/src/H5config.h \
 	$(top_builddir)/fortran/src/H5config_f.inc
 CONFIG_CLEAN_FILES =
 CONFIG_CLEAN_VPATH_FILES =
-am__installdirs = "$(DESTDIR)$(bindir)"
-PROGRAMS = $(bin_PROGRAMS)
+PROGRAMS = $(noinst_PROGRAMS)
 h5tools_test_utils_SOURCES = h5tools_test_utils.c
 h5tools_test_utils_OBJECTS = h5tools_test_utils.$(OBJEXT)
 h5tools_test_utils_LDADD = $(LDADD)
@@ -452,7 +460,6 @@ CCDEPMODE = @CCDEPMODE@
 CC_VERSION = @CC_VERSION@
 CFLAGS = @CFLAGS@
 CLANG_SANITIZE_CHECKS = @CLANG_SANITIZE_CHECKS@
-CODESTACK = @CODESTACK@
 CONFIG_DATE = @CONFIG_DATE@
 CONFIG_MODE = @CONFIG_MODE@
 CONFIG_USER = @CONFIG_USER@
@@ -538,6 +545,7 @@ FCFLAGS_f90 = @FCFLAGS_f90@
 FCLIBS = @FCLIBS@
 FC_VERSION = @FC_VERSION@
 FGREP = @FGREP@
+FORTRAN_C_BOOL_IS_UNIQUE = @FORTRAN_C_BOOL_IS_UNIQUE@
 FORTRAN_C_LONG_DOUBLE_IS_UNIQUE = @FORTRAN_C_LONG_DOUBLE_IS_UNIQUE@
 FORTRAN_HAVE_C_LONG_DOUBLE = @FORTRAN_HAVE_C_LONG_DOUBLE@
 FSEARCH_DIRS = @FSEARCH_DIRS@
@@ -567,9 +575,11 @@ H5_UTILS_TEST_BUILDDIR = @H5_UTILS_TEST_BUILDDIR@
 H5_VERSION = @H5_VERSION@
 HADDR_T = @HADDR_T@
 HAVE_Fortran_INTEGER_SIZEOF_16 = @HAVE_Fortran_INTEGER_SIZEOF_16@
+HAVE_ISO_FORTRAN_ENV = @HAVE_ISO_FORTRAN_ENV@
 HAVE_LIBHDFS = @HAVE_LIBHDFS@
 HAVE_MERCURY = @HAVE_MERCURY@
 HAVE_PTHREAD = @HAVE_PTHREAD@
+HAVE__FLOAT16 = @HAVE__FLOAT16@
 HDF5_DOXYGEN = @HDF5_DOXYGEN@
 HDF5_DOXY_WARNINGS = @HDF5_DOXY_WARNINGS@
 HDF5_HL = @HDF5_HL@
@@ -626,6 +636,7 @@ MANIFEST_TOOL = @MANIFEST_TOOL@
 MAP_API = @MAP_API@
 MIRROR_VFD = @MIRROR_VFD@
 MKDIR_P = @MKDIR_P@
+MPI_LOGICAL_KIND = @MPI_LOGICAL_KIND@
 NM = @NM@
 NMEDIT = @NMEDIT@
 OBJDUMP = @OBJDUMP@
@@ -654,6 +665,7 @@ PAC_FORTRAN_NATIVE_INTEGER_SIZEOF = @PAC_FORTRAN_NATIVE_INTEGER_SIZEOF@
 PAC_FORTRAN_NATIVE_REAL_KIND = @PAC_FORTRAN_NATIVE_REAL_KIND@
 PAC_FORTRAN_NATIVE_REAL_SIZEOF = @PAC_FORTRAN_NATIVE_REAL_SIZEOF@
 PAC_FORTRAN_NUM_INTEGER_KINDS = @PAC_FORTRAN_NUM_INTEGER_KINDS@
+PAC_MPI_LOGICAL_KIND = @PAC_MPI_LOGICAL_KIND@
 PARALLEL = @PARALLEL@
 PARALLEL_FILTERED_WRITES = @PARALLEL_FILTERED_WRITES@
 PARALLEL_TOOLS = @PARALLEL_TOOLS@
@@ -671,6 +683,7 @@ SEARCH = @SEARCH@
 SED = @SED@
 SET_MAKE = @SET_MAKE@
 SHELL = @SHELL@
+SHOW_ALL_WARNINGS = @SHOW_ALL_WARNINGS@
 SIZE_T = @SIZE_T@
 STATIC_EXEC = @STATIC_EXEC@
 STATIC_SHARED = @STATIC_SHARED@
@@ -831,8 +844,8 @@ TEST_PROG_CHKEXE = $(TEST_PROG:=.chkexe_)
 TEST_PROG_PARA_CHKEXE = $(TEST_PROG_PARA:=.chkexe_)
 TEST_SCRIPT_CHKSH = $(TEST_SCRIPT:=.chkexe_)
 TEST_SCRIPT_PARA_CHKSH = $(TEST_SCRIPT_PARA:=.chkexe_)
-VFD_LIST = sec2 stdio core core_paged split multi family splitter \
-	$(am__append_1) $(am__append_2) $(am__append_3)
+VFD_LIST = sec2 stdio core core_paged split multi family \
+	$(am__append_1)
 
 # Test with just the native connector, with a single pass-through connector
 # and with a doubly-stacked pass-through.
@@ -876,49 +889,9 @@ $(top_srcdir)/configure: @MAINTAINER_MODE_TRUE@ $(am__configure_deps)
 $(ACLOCAL_M4): @MAINTAINER_MODE_TRUE@ $(am__aclocal_m4_deps)
 	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
 $(am__aclocal_m4_deps):
-install-binPROGRAMS: $(bin_PROGRAMS)
-	@$(NORMAL_INSTALL)
-	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
-	if test -n "$$list"; then \
-	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
-	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
-	fi; \
-	for p in $$list; do echo "$$p $$p"; done | \
-	sed 's/$(EXEEXT)$$//' | \
-	while read p p1; do if test -f $$p \
-	 || test -f $$p1 \
-	  ; then echo "$$p"; echo "$$p"; else :; fi; \
-	done | \
-	sed -e 'p;s,.*/,,;n;h' \
-	    -e 's|.*|.|' \
-	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
-	sed 'N;N;N;s,\n, ,g' | \
-	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
-	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
-	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
-	    else { print "f", $$3 "/" $$4, $$1; } } \
-	  END { for (d in files) print "f", d, files[d] }' | \
-	while read type dir files; do \
-	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
-	    test -z "$$files" || { \
-	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
-	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
-	    } \
-	; done
 
-uninstall-binPROGRAMS:
-	@$(NORMAL_UNINSTALL)
-	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
-	files=`for p in $$list; do echo "$$p"; done | \
-	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
-	      -e 's/$$/$(EXEEXT)/' \
-	`; \
-	test -n "$$list" || exit 0; \
-	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
-	cd "$(DESTDIR)$(bindir)" && rm -f $$files
-
-clean-binPROGRAMS:
-	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
+clean-noinstPROGRAMS:
+	@list='$(noinst_PROGRAMS)'; test -n "$$list" || exit 0; \
 	echo " rm -f" $$list; \
 	rm -f $$list || exit $$?; \
 	test -n "$(EXEEXT)" || exit 0; \
@@ -1209,9 +1182,6 @@ check-am: all-am
 check: check-am
 all-am: Makefile $(PROGRAMS) all-local
 installdirs:
-	for dir in "$(DESTDIR)$(bindir)"; do \
-	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
-	done
 install: install-am
 install-exec: install-exec-am
 install-data: install-data-am
@@ -1247,7 +1217,8 @@ maintainer-clean-generic:
 	@echo "it deletes files that may require special tools to rebuild."
 clean: clean-am
 
-clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am
+clean-am: clean-generic clean-libtool clean-noinstPROGRAMS \
+	mostlyclean-am
 
 distclean: distclean-am
 		-rm -f ./$(DEPDIR)/h5tools_test_utils.Po
@@ -1273,7 +1244,7 @@ install-dvi: install-dvi-am
 
 install-dvi-am:
 
-install-exec-am: install-binPROGRAMS
+install-exec-am:
 
 install-html: install-html-am
 
@@ -1313,25 +1284,24 @@ ps: ps-am
 
 ps-am:
 
-uninstall-am: uninstall-binPROGRAMS
+uninstall-am:
 
 .MAKE: check-am install-am install-strip
 
 .PHONY: CTAGS GTAGS TAGS all all-am all-local am--depfiles check \
-	check-TESTS check-am clean clean-binPROGRAMS clean-generic \
-	clean-libtool cscopelist-am ctags ctags-am distclean \
+	check-TESTS check-am clean clean-generic clean-libtool \
+	clean-noinstPROGRAMS cscopelist-am ctags ctags-am distclean \
 	distclean-compile distclean-generic distclean-libtool \
 	distclean-tags distdir dvi dvi-am html html-am info info-am \
-	install install-am install-binPROGRAMS install-data \
-	install-data-am install-dvi install-dvi-am install-exec \
-	install-exec-am install-html install-html-am install-info \
-	install-info-am install-man install-pdf install-pdf-am \
-	install-ps install-ps-am install-strip installcheck \
-	installcheck-am installdirs maintainer-clean \
-	maintainer-clean-generic mostlyclean mostlyclean-compile \
-	mostlyclean-generic mostlyclean-libtool mostlyclean-local pdf \
-	pdf-am ps ps-am recheck tags tags-am uninstall uninstall-am \
-	uninstall-binPROGRAMS
+	install install-am install-data install-data-am install-dvi \
+	install-dvi-am install-exec install-exec-am install-html \
+	install-html-am install-info install-info-am install-man \
+	install-pdf install-pdf-am install-ps install-ps-am \
+	install-strip installcheck installcheck-am installdirs \
+	maintainer-clean maintainer-clean-generic mostlyclean \
+	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
+	mostlyclean-local pdf pdf-am ps ps-am recheck tags tags-am \
+	uninstall uninstall-am
 
 .PRECIOUS: Makefile
 
@@ -1466,15 +1436,15 @@ $(TEST_PROG_CHKEXE) $(TEST_PROG_PARA_CHKEXE) dummy.chkexe_:
                 if test -n "$(HDF5_VOL_CONNECTOR)"; then \
                   echo "VOL connector: $(HDF5_VOL_CONNECTOR)" | tee -a $${log}; \
                 fi; \
-                if test -n "$(HDF5_DRIVER)"; then \
-                  echo "Virtual file driver (VFD): $(HDF5_DRIVER)" | tee -a $${log}; \
+                if test -n "$(HDF5_TEST_DRIVER)"; then \
+                  echo "Virtual file driver (VFD): $(HDF5_TEST_DRIVER)" | tee -a $${log}; \
                 fi; \
               else \
                 if test -n "$(HDF5_VOL_CONNECTOR)"; then \
                   echo "VOL connector: $(HDF5_VOL_CONNECTOR)" >> $${log}; \
                 fi; \
-                if test -n "$(HDF5_DRIVER)"; then \
-                  echo "Virtual file driver (VFD): $(HDF5_DRIVER)" >> $${log}; \
+                if test -n "$(HDF5_TEST_DRIVER)"; then \
+                  echo "Virtual file driver (VFD): $(HDF5_TEST_DRIVER)" >> $${log}; \
                 fi; \
               fi; \
               if test -n "$(REALTIMEOUTPUT)"; then \
@@ -1591,20 +1561,23 @@ build-check-p: $(LIB) $(PROGS) $(chk_TESTS)
 @MIRROR_VFD_CONDITIONAL_TRUE@  # Mirror VFD needs network configuration, etc. and isn't easy to set
 @MIRROR_VFD_CONDITIONAL_TRUE@  # reasonable defaults for that info.
 @MIRROR_VFD_CONDITIONAL_TRUE@  # VFD_LIST += mirror
-@SUBFILING_VFD_CONDITIONAL_TRUE@  # Several VFD tests fail with Subfiling since it
-@SUBFILING_VFD_CONDITIONAL_TRUE@  # doesn't currently support collective I/O
+@ROS3_VFD_CONDITIONAL_TRUE@  # This would require a custom test suite
+@ROS3_VFD_CONDITIONAL_TRUE@  # VFD_LIST += ros3
+@HDFS_VFD_CONDITIONAL_TRUE@  # This would require a custom test suite
+@HDFS_VFD_CONDITIONAL_TRUE@  # VFD_LIST += hdfs
+@SUBFILING_VFD_CONDITIONAL_TRUE@  # Subfiling has a few VFD test failures to be resolved
 @SUBFILING_VFD_CONDITIONAL_TRUE@  # VFD_LIST += subfiling
 
 # Run test with different Virtual File Driver
 check-vfd: $(LIB) $(PROGS) $(chk_TESTS)
-	@for vfd in $(VFD_LIST) dummy; do                                     \
-	    if test $$vfd != dummy; then                                      \
-	        echo "============================";                          \
-	        echo "Testing Virtual File Driver $$vfd";                     \
-	        echo "============================";                          \
-	        $(MAKE) $(AM_MAKEFLAGS) check-clean || exit 1;                \
-	        HDF5_DRIVER=$$vfd $(MAKE) $(AM_MAKEFLAGS) check || exit 1;    \
-	    fi;                                                               \
+	@for vfd in $(VFD_LIST) dummy; do                                          \
+	    if test $$vfd != dummy; then                                           \
+	        echo "============================";                               \
+	        echo "Testing Virtual File Driver $$vfd";                          \
+	        echo "============================";                               \
+	        $(MAKE) $(AM_MAKEFLAGS) check-clean || exit 1;                     \
+	        HDF5_TEST_DRIVER=$$vfd $(MAKE) $(AM_MAKEFLAGS) check || exit 1;    \
+	    fi;                                                                    \
 	done
 
 # Run test with different passthrough Virtual Object Layer Connector
diff --git a/tools/test/h5repack/h5repack.sh.in b/tools/test/h5repack/h5repack.sh.in
--- a/tools/test/h5repack/h5repack.sh.in
+++ b/tools/test/h5repack/h5repack.sh.in
@@ -858,6 +858,11 @@ TOOLTESTV()
 
     # display output compare
     STDOUT_FILTER $actual
+    tmp_file=/tmp/h5test_tmp_$$
+    cp $actual $tmp_file
+    sed -e 's/GZIP   (0\.[0-9][0-9][0-9]:1)/GZIP   (0.XXX:1)/' \
+    < $tmp_file > $actual
+    rm -f $tmp_file
     cat $actual_err >> $actual
 
     VERIFY output from $H5REPACK $@
@@ -1056,7 +1061,7 @@ TOOLTESTM() {
     cp $actual_err $actual_err_sav
 
     # Extract file name, line number, version and thread IDs because they may be different
-    sed -e 's/thread [0-9]*/thread (IDs)/' -e 's/: .*\.c /: (file name) /' \
+    sed -e 's/ thread [0-9]*//' -e 's/: .*\.c /: (file name) /' \
         -e 's/line [0-9]*/line (number)/' \
         -e 's/v[1-9]*\.[0-9]*\./version (number)\./' \
         -e 's/[1-9]*\.[0-9]*\.[0-9]*[^)]*/version (number)/' \
@@ -1122,6 +1127,63 @@ TOOLTEST_DUMP()
      RET=$?
 
     fi
+
+    if cmp -s $expect $actual; then
+     echo " PASSED"
+    else
+     echo "*FAILED*"
+     echo "    Expected result (*.ddl) differs from actual result (*.out)"
+     nerrors="`expr $nerrors + 1`"
+     test yes = "$verbose" && diff -c $expect $actual |sed 's/^/    /'
+    fi
+
+   rm -f $actual $actual_err
+   rm -f $outfile
+}
+
+# This is same as TOOLTESTV() with comparing h5dump output
+# from -pH option and MASK out compression
+#
+TOOLTEST_DUMP_MASK()
+{
+    infile=$2
+    outfile=out-$1.$2
+    expect="$TESTDIR/$1.$2.ddl"
+    actual="$TESTDIR/out-$1.$2.out"
+    actual_err="$TESTDIR/out-$1.$2.err"
+
+    shift
+    shift
+
+    # Run test.
+    TESTING $H5REPACK $@
+    (
+        cd $TESTDIR
+        $RUNSERIAL $H5REPACK_BIN "$@" $infile $outfile
+    ) >$actual 2>$actual_err
+    RET=$?
+    if [ $RET != 0 ] ; then
+    echo "*FAILED*"
+    nerrors="`expr $nerrors + 1`"
+    else
+     echo " PASSED"
+     VERIFY h5dump output $@
+     (
+        cd $TESTDIR
+        $RUNSERIAL $H5DUMP_BIN -q creation_order -pH $outfile
+     ) >$actual 2>$actual_err
+     cat $actual_err >> $actual
+
+     RET=$?
+
+    fi
+
+    tmp_file=/tmp/h5test_tmp_$$
+    cp $actual $tmp_file
+    sed -e 's/SIZE [0-9][0-9][0-9][0-9] (2\.[0-9][0-9][0-9]:1 COMPRESSION)/SIZE XXXX (2.XXX:1 COMPRESSION)/' \
+    < $tmp_file > $actual
+    rm -f $tmp_file
+    cat $actual_err >> $actual
 
     if cmp -s $expect $actual; then
      echo " PASSED"
@@ -1570,11 +1632,11 @@ fi
 
 
 #limit
-arg="h5repack_layout.h5 -f GZIP=1 -m 1024"
+arg="h5repack_layout.h5 -f GZIP=2 -m 1024"
 if test $USE_FILTER_DEFLATE != "yes"  ; then
  SKIP $arg
 else
- TOOLTEST_DUMP deflate_limit $arg
+ TOOLTEST_DUMP_MASK deflate_limit $arg
 fi
 
 #file
@@ -1742,6 +1804,10 @@ fi
 # add a userblock to file
 arg="h5repack_objs.h5 -u ublock.bin -b 2048"
 TOOLTEST add_userblock $arg
+
+# reserve a userblock to file
+arg="h5repack_objs.h5 -b 2048"
+TOOLTEST reserve_userblock $arg
 
 # add alignment
 arg="h5repack_objs.h5 -t 1 -a 1 "
